plugins {
	id 'java'                                   // если в корне есть тесты или общие задачи
	id 'io.spring.dependency-management' version '1.1.7'  // управление версиями
}


group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

// Общее управление версиями для всех подмодулей
dependencyManagement {
	imports {
		mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.10"
	}
}

// Общие настройки для всех подмодулей
subprojects {
	apply plugin: 'java'
	apply plugin: 'io.spring.dependency-management'

	group = rootProject.group
	version = rootProject.version

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(17)
		}
	}

	repositories {
		mavenCentral()
	}

	dependencyManagement {
		imports {
			mavenBom "org.springframework.boot:spring-boot-dependencies:3.5.10"
		}
	}

	// Общие зависимости для всех подмодулей (если нужны)
	dependencies {
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
	}

	test {
		useJUnitPlatform()
	}
}