spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres_secret
    username: postgres
    url: jdbc:postgresql://localhost/orders
  application:
    name: order-platform
  jpa:
    hibernate:
      ddl-auto: update
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/changelog-master.xml
#    default-schema: public
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: all
#      retries: 3
jwt:
  secret: "mySuperSecretKeyForJWT_64chars_minimum__________CHANGE_ME_1234567890"
  expiration: 86400000
server:
  port: 8080